'use strict';

const express = require('express');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const { Pool } = require('pg');
const multer = require('multer');
const pdfParse = require('pdf-parse');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const nodemailer = require('nodemailer');
const Stripe = require('stripe');
const { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } = require('@aws-sdk/client-s3');
const { createRemoteJWKSet, jwtVerify } = require('jose');

const app = express();
const PORT = Number(process.env.PORT || 3000);
const VERSION = '3.0.0';
const APP_NAME = process.env.APP_NAME || 'DocFlow';
const JWT_SECRET = process.env.JWT_SECRET || (process.env.NODE_ENV === 'production' ? null : 'dev-only-change-me');
const DATABASE_URL = process.env.DATABASE_URL || null;
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const UPLOAD_DIR = path.join(DATA_DIR, 'uploads');
const MAX_FILE_MB = Number(process.env.MAX_FILE_MB || 25);
const MAX_BATCH = Number(process.env.MAX_BATCH_FILES || 20);
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY ? crypto.createHash('sha256').update(process.env.ENCRYPTION_KEY).digest() : null;
fs.mkdirSync(UPLOAD_DIR, { recursive: true });
if (process.env.NODE_ENV === 'production' && (!JWT_SECRET || !ENCRYPTION_KEY)) throw new Error('JWT_SECRET and ENCRYPTION_KEY are required in production');

const pool = DATABASE_URL ? new Pool({
  connectionString: DATABASE_URL,
  ssl: process.env.PGSSL_DISABLE === 'true' ? false : { rejectUnauthorized: false },
  max: Number(process.env.PGPOOL_MAX || 20),
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000
}) : null;
const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;
const s3 = process.env.S3_BUCKET ? new S3Client({
  region: process.env.S3_REGION || 'auto',
  endpoint: process.env.S3_ENDPOINT || undefined,
  forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
  credentials: process.env.S3_ACCESS_KEY_ID ? { accessKeyId: process.env.S3_ACCESS_KEY_ID, secretAccessKey: process.env.S3_SECRET_ACCESS_KEY } : undefined
}) : null;
const storageMode = s3 ? 's3' : 'local';

const upload = multer({
  dest: UPLOAD_DIR,
  limits: { fileSize: MAX_FILE_MB * 1024 * 1024, files: MAX_BATCH, fields: 30 },
  fileFilter: (_req, file, cb) => {
    const allowed = new Set(['application/pdf', 'image/png', 'image/jpeg', 'image/webp', 'image/tiff']);
    cb(null, allowed.has(file.mimetype));
  }
});

app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false, crossOriginOpenerPolicy: { policy: 'same-origin-allow-popups' } }));
app.use(express.json({ limit: '2mb', verify: (req, _res, buf) => { if (req.originalUrl === '/api/billing/stripe/webhook' || req.originalUrl === '/api/billing/paystack/webhook') req.rawBody = Buffer.from(buf); } }));
app.use(express.urlencoded({ extended: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: Number(process.env.RATE_LIMIT || 900), standardHeaders: true, legacyHeaders: false }));
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: Number(process.env.AUTH_RATE_LIMIT || 30), standardHeaders: true, legacyHeaders: false });
const uploadLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: Number(process.env.UPLOAD_RATE_LIMIT || 120), standardHeaders: true, legacyHeaders: false });
app.use((req, res, next) => { req.requestId = crypto.randomUUID(); res.setHeader('X-Request-ID', req.requestId); next(); });
app.use((req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); next(); });

async function q(text, params = []) {
  if (!pool) throw new Error('Database not configured');
  return pool.query(text, params);
}
function requireDb(_req, res, next) { if (!pool) return res.status(503).json({ error: 'Database not configured', requestId: _req.requestId }); next(); }
function slugify(value) { return String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'workspace'; }
function hash(value) { return crypto.createHash('sha256').update(value).digest('hex'); }
function apiKeyMake() { const raw = 'df_live_' + crypto.randomBytes(32).toString('hex'); return { raw, prefix: raw.slice(0, 18), digest: hash(raw) }; }
function randomToken(bytes = 32) { return crypto.randomBytes(bytes).toString('hex'); }
function signToken(user, extra = {}) { return jwt.sign({ sub: user.id, orgId: user.org_id, role: user.role, tokenVersion: user.token_version || 0, ...extra }, JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES || '12h' }); }
function jsonSafe(v) { return v == null ? {} : JSON.parse(JSON.stringify(v)); }
function sanitizeFilename(name) { return path.basename(String(name || 'document')).replace(/[\0<>:"/\\|?*]/g, '_').slice(0, 200) || 'document'; }
function csvEscape(v) { return '"' + String(v ?? '').replaceAll('"', '""') + '"'; }

function isPrivateHostname(hostname){const h=String(hostname||'').toLowerCase().replace(/^\[|\]$/g,'');if(['localhost','localhost.localdomain'].includes(h)||h.endsWith('.localhost')||h.endsWith('.local'))return true;const m=h.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);if(!m)return false;const n=m.slice(1).map(Number);if(n.some(x=>x>255))return true;const [a,b]=n;return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===0);}
function validateWebhookUrl(raw){const u=new URL(String(raw||''));if(u.protocol!=='https:' && !(process.env.NODE_ENV!=='production'&&u.protocol==='http:'))throw Object.assign(new Error('Webhook URL must use HTTPS in production'),{statusCode:400});if(isPrivateHostname(u.hostname)&&process.env.ALLOW_PRIVATE_WEBHOOKS!=='true')throw Object.assign(new Error('Private/internal webhook destinations are blocked by default'),{statusCode:400});return u.toString();}
function normalizeEmail(v) { return String(v || '').trim().toLowerCase(); }
function validEmail(v) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v || '')); }
const API_SCOPES = new Set(['documents:read','documents:write','workflows:read','workflows:write','approvals:read','approvals:write','exports:read']);
function normalizeScopes(scopes) { return [...new Set((Array.isArray(scopes) ? scopes : []).map(String).filter(x => API_SCOPES.has(x)))]; }
function fileMagicValid(file) {
  const b = fs.readFileSync(file.path);
  if (file.mimetype === 'application/pdf') return b.slice(0,5).toString('ascii') === '%PDF-';
  if (file.mimetype === 'image/png') return b.slice(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));
  if (file.mimetype === 'image/jpeg') return b.slice(0,3).equals(Buffer.from([0xff,0xd8,0xff]));
  if (file.mimetype === 'image/webp') return b.slice(0,4).toString('ascii') === 'RIFF' && b.slice(8,12).toString('ascii') === 'WEBP';
  if (file.mimetype === 'image/tiff') return b.slice(0,4).equals(Buffer.from([0x49,0x49,0x2a,0x00])) || b.slice(0,4).equals(Buffer.from([0x4d,0x4d,0x00,0x2a]));
  return false;
}
function parseMoney(v) { const n=Number(String(v||'').replace(/[^0-9.-]/g,'')); return Number.isFinite(n) ? n : null; }
function validateExtraction(type, data) {
  const errors=[]; const d=data||{};
  if(type==='invoice') {
    if(!d.invoice_number) errors.push('invoice_number_missing');
    if(!d.date) errors.push('date_missing');
    const total=parseMoney(d.total), subtotal=parseMoney(d.subtotal), tax=parseMoney(d.tax);
    if(total!==null && subtotal!==null && tax!==null && Math.abs((subtotal+tax)-total)>0.02) errors.push('invoice_total_mismatch');
  }
  return {status:errors.length ? 'needs_review' : 'valid', errors};
}
function securityEvent(event, req, metadata={}) { return audit(req?.user?.org_id || metadata.org_id, req?.user?.id || null, `security.${event}`, 'security', req?.requestId || null, metadata); }

function encrypt(value) {
  if (!value || !ENCRYPTION_KEY) return value || null;
  const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', ENCRYPTION_KEY, iv);
  const enc = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]);
  return [iv.toString('base64url'), cipher.getAuthTag().toString('base64url'), enc.toString('base64url')].join('.');
}
function decrypt(value) {
  if (!value || !ENCRYPTION_KEY || !String(value).includes('.')) return value || null;
  const [ivB64, tagB64, encB64] = String(value).split('.');
  try { const decipher = crypto.createDecipheriv('aes-256-gcm', ENCRYPTION_KEY, Buffer.from(ivB64, 'base64url')); decipher.setAuthTag(Buffer.from(tagB64, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(encB64, 'base64url')), decipher.final()]).toString('utf8'); } catch (_) { return null; }
}

async function audit(orgId, userId, action, entityType, entityId, metadata = {}) {
  try { await q(`INSERT INTO audit_logs(org_id,user_id,action,entity_type,entity_id,metadata,created_at) VALUES($1,$2,$3,$4,$5,$6,NOW())`, [orgId, userId || null, action, entityType || null, entityId || null, jsonSafe(metadata)]); } catch (_) {}
}

const PLAN_LIMITS = {
  trial: { documents: 250, storageMb: 500 },
  starter: { documents: 1000, storageMb: 2000 },
  business: { documents: 10000, storageMb: 20000 },
  enterprise: { documents: Number.MAX_SAFE_INTEGER, storageMb: Number.MAX_SAFE_INTEGER }
};
async function usage(orgId) {
  const [docs, bytes, month] = await Promise.all([
    q(`SELECT COUNT(*)::int count FROM documents WHERE org_id=$1`, [orgId]),
    q(`SELECT COALESCE(SUM(size_bytes),0)::bigint bytes FROM documents WHERE org_id=$1`, [orgId]),
    q(`SELECT COUNT(*)::int count FROM usage_events WHERE org_id=$1 AND created_at >= date_trunc('month',NOW())`, [orgId])
  ]);
  return { documents: docs.rows[0].count, bytes: Number(bytes.rows[0].bytes), eventsThisMonth: month.rows[0].count };
}
async function enforceUsage(orgId, incomingBytes = 0) {
  const org = (await q('SELECT plan FROM organizations WHERE id=$1', [orgId])).rows[0];
  const plan = PLAN_LIMITS[org?.plan || 'trial'] || PLAN_LIMITS.trial;
  const u = await usage(orgId);
  if (u.documents + 1 > plan.documents) throw Object.assign(new Error('Document volume limit reached for the current plan'), { statusCode: 402 });
  if ((u.bytes + incomingBytes) > plan.storageMb * 1024 * 1024) throw Object.assign(new Error('Storage limit reached for the current plan'), { statusCode: 402 });
  return { u, plan };
}

async function storagePut(filePath, objectKey, mimeType) {
  if (storageMode === 'local') return { key: filePath, mode: 'local' };
  const body = fs.createReadStream(filePath);
  await s3.send(new PutObjectCommand({ Bucket: process.env.S3_BUCKET, Key: objectKey, Body: body, ContentType: mimeType, ServerSideEncryption: process.env.S3_SSE || undefined }));
  return { key: objectKey, mode: 's3' };
}
async function storageGet(key) {
  if (storageMode === 'local') return { stream: fs.createReadStream(key) };
  const obj = await s3.send(new GetObjectCommand({ Bucket: process.env.S3_BUCKET, Key: key }));
  return { stream: obj.Body, contentType: obj.ContentType, contentLength: obj.ContentLength };
}
async function storageDelete(key) {
  if (storageMode === 'local') { try { fs.unlinkSync(key); } catch (_) {} return; }
  await s3.send(new DeleteObjectCommand({ Bucket: process.env.S3_BUCKET, Key: key }));
}

function base32Encode(bytes) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = ''; let out = '';
  for (const b of bytes) bits += b.toString(2).padStart(8, '0');
  for (let i = 0; i < bits.length; i += 5) out += alphabet[parseInt(bits.slice(i, i + 5).padEnd(5, '0'), 2)];
  return out;
}
function base32Decode(input) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = ''; const cleaned = String(input).replace(/=+$/,'').toUpperCase();
  for (const ch of cleaned) { const idx = alphabet.indexOf(ch); if (idx < 0) throw new Error('Invalid TOTP secret'); bits += idx.toString(2).padStart(5,'0'); }
  const out=[]; for (let i=0;i+8<=bits.length;i+=8) out.push(parseInt(bits.slice(i,i+8),2)); return Buffer.from(out);
}
function totp(secret, counter = Math.floor(Date.now()/1000/30)) {
  const key=base32Decode(secret); const msg=Buffer.alloc(8); msg.writeBigUInt64BE(BigInt(counter)); const h=crypto.createHmac('sha1',key).update(msg).digest(); const off=h[h.length-1]&15; const bin=((h[off]&127)<<24)|((h[off+1]&255)<<16)|((h[off+2]&255)<<8)|(h[off+3]&255); return String(bin%1000000).padStart(6,'0');
}
function totpVerify(secret, code) { const now=Math.floor(Date.now()/1000/30); return [-1,0,1].some(delta=>totp(secret, now+delta)===String(code).padStart(6,'0')); }

async function sendMail(to, subject, text) {
  if (!process.env.SMTP_HOST) return false;
  const transport = nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined });
  await transport.sendMail({ from: process.env.SMTP_FROM || process.env.SMTP_USER, to, subject, text });
  return true;
}

async function ocrFile(filePath) {
  if (!process.env.OCR_API_URL) return { text: '', note: 'OCR is not configured.' };
  const bytes = fs.readFileSync(filePath); const form = new FormData(); form.append('file', new Blob([bytes]), path.basename(filePath)); form.append('language', process.env.OCR_LANGUAGE || 'eng'); form.append('isOverlayRequired','false');
  const headers={}; if(process.env.OCR_API_KEY) headers.apikey=process.env.OCR_API_KEY;
  const r=await fetch(process.env.OCR_API_URL,{method:'POST',headers,body:form}); if(!r.ok) throw new Error(`OCR provider error ${r.status}`); const body=await r.json();
  const text=(body?.ParsedResults||[]).map(x=>x?.ParsedText||'').join('\n').trim(); if(!text) throw new Error(body?.ErrorMessage||'OCR provider returned no text'); return {text,pages:body?.ParsedResults?.length||null};
}
async function parseDocument(filePath,mimeType) {
  const buffer=fs.readFileSync(filePath);
  if(mimeType==='application/pdf') { const parsed=await pdfParse(buffer); const text=(parsed.text||'').trim(); if(text.length>=20) return {text,pages:parsed.numpages||null,mode:'pdf-text'}; try { const ocr=await ocrFile(filePath); return {...ocr,mode:'ocr'}; } catch(e) { return {text:'',note:e.message}; } }
  try { const ocr=await ocrFile(filePath); return {...ocr,mode:'ocr'}; } catch(e) { return {text:'',note:e.message}; }
}
function deterministicExtract(text) {
  const source=String(text||''), out={};
  const patterns=[['invoice_number',/(invoice\s*(?:number|no\.?|#)\s*[:\-]?\s*)([A-Z0-9\-\/]+)/i],['date',/(?:invoice\s*)?date\s*[:\-]?\s*(\d{1,4}[\/\-]\d{1,2}[\/\-]\d{1,4})/i],['customer',/(?:bill\s*to|customer|client)\s*[:\-]?\s*([^\n]+)/i],['total',/(?:grand\s*total|total\s*due|amount\s*due|total)\s*[:\-]?\s*([₦$€£]?\s?[\d,]+(?:\.\d{2})?)/i],['currency',/\b(NGN|USD|EUR|GBP)\b/i]];
  for(const [k,re] of patterns){const m=source.match(re);if(m) out[k]=(m[2]||m[1]||'').trim();}
  const sub=[...source.matchAll(/(?:subtotal|sub-total)\s*[:\-]?\s*([₦$€£]?\s?[\d,]+(?:\.\d{2})?)/ig)]; if(sub[0]) out.subtotal=sub[0][1].trim();
  return out;
}
async function aiExtract(text,documentType,schema) {
  const apiKey=process.env.AI_API_KEY; const base=(process.env.AI_BASE_URL||'https://api.openai.com/v1').replace(/\/$/,''); const model=process.env.AI_MODEL||'gpt-4o-mini';
  if(!apiKey) return {data:deterministicExtract(text),confidence:68,mode:'deterministic'};
  const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),Number(process.env.AI_TIMEOUT_MS||25000));
  try {
    const schemaText=schema?JSON.stringify(schema):'Return useful fields for the document without inventing values.';
    const prompt=`Extract structured business data. Document type: ${documentType||'unknown'}. Extraction requirements: ${schemaText}. Return ONLY valid JSON. Preserve amounts as strings. Never invent values. DOCUMENT:\n${String(text).slice(0,45000)}`;
    const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model,temperature:0,messages:[{role:'system',content:'You are a precise enterprise document extraction engine.'},{role:'user',content:prompt}]}),signal:controller.signal}); if(!r.ok) throw new Error(`AI provider error ${r.status}`);
    const body=await r.json(); const content=body?.choices?.[0]?.message?.content||'{}'; const match=content.match(/\{[\s\S]*\}/); const data=match?JSON.parse(match[0]):{}; return {data,confidence:91,mode:'ai'};
  } catch(e) { return {data:deterministicExtract(text),confidence:63,mode:'fallback',error:e.message}; } finally { clearTimeout(timeout); }
}
function riskFor(data) { const s=JSON.stringify(data).toLowerCase(); if(/sanction|litigation|lawsuit|fraud|bank account|wire transfer|bankruptcy/.test(s)) return 'high'; if(/overdue|penalty|urgent|legal|termination/.test(s)) return 'medium'; return 'low'; }

async function ensureSchema() {
  if(!pool) return;
  await q(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);
  await q(`CREATE TABLE IF NOT EXISTS organizations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,plan TEXT NOT NULL DEFAULT 'trial',trial_ends_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,email TEXT NOT NULL,password_hash TEXT NOT NULL,full_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',status TEXT NOT NULL DEFAULT 'active',token_version INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(org_id,email))`);
  await q(`CREATE TABLE IF NOT EXISTS documents(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL,name TEXT NOT NULL,original_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes BIGINT NOT NULL,storage_key TEXT NOT NULL,storage_mode TEXT NOT NULL DEFAULT 'local',sha256 TEXT,checksum TEXT,status TEXT NOT NULL DEFAULT 'queued',document_type TEXT NOT NULL DEFAULT 'unknown',extracted_text TEXT,extracted_data JSONB NOT NULL DEFAULT '{}'::jsonb,confidence NUMERIC(5,2),risk_level TEXT NOT NULL DEFAULT 'low',error_message TEXT,pages INT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),processed_at TIMESTAMPTZ)`);
  await q(`CREATE TABLE IF NOT EXISTS approvals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,document_id UUID REFERENCES documents(id) ON DELETE CASCADE,requested_by UUID REFERENCES users(id),approver_role TEXT NOT NULL DEFAULT 'admin',status TEXT NOT NULL DEFAULT 'pending',note TEXT,decided_by UUID REFERENCES users(id),decided_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS workflows(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT,enabled BOOLEAN NOT NULL DEFAULT true,trigger_type TEXT NOT NULL,definition JSONB NOT NULL DEFAULT '{}'::jsonb,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS workflow_runs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,workflow_id UUID REFERENCES workflows(id) ON DELETE SET NULL,document_id UUID REFERENCES documents(id) ON DELETE SET NULL,status TEXT NOT NULL DEFAULT 'running',output JSONB NOT NULL DEFAULT '{}'::jsonb,error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),finished_at TIMESTAMPTZ)`);
  await q(`CREATE TABLE IF NOT EXISTS api_keys(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name TEXT NOT NULL,key_prefix TEXT NOT NULL,key_hash TEXT NOT NULL UNIQUE,revoked BOOLEAN NOT NULL DEFAULT false,scopes JSONB NOT NULL DEFAULT '["documents:read","documents:write"]'::jsonb,created_by UUID REFERENCES users(id),last_used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,user_id UUID REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,entity_type TEXT,entity_id TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS billing_customers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID UNIQUE NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,stripe_customer_id TEXT,paystack_customer_code TEXT,email TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS organization_settings(org_id UUID PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,retention_days INT NOT NULL DEFAULT 365,require_approval_for_high_risk BOOLEAN NOT NULL DEFAULT true,allowed_email_domain TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS usage_events(id BIGSERIAL PRIMARY KEY,org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,event_type TEXT NOT NULL,document_id UUID REFERENCES documents(id) ON DELETE SET NULL,units INT NOT NULL DEFAULT 1,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS job_queue(id BIGSERIAL PRIMARY KEY,org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,status TEXT NOT NULL DEFAULT 'queued',attempts INT NOT NULL DEFAULT 0,max_attempts INT NOT NULL DEFAULT 5,available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),locked_at TIMESTAMPTZ,locked_by TEXT,error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),finished_at TIMESTAMPTZ)`);
  await q(`CREATE TABLE IF NOT EXISTS invites(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,email TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'pending',invited_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS mfa_methods(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL DEFAULT 'totp',secret_enc TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS password_resets(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS oidc_states(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID REFERENCES organizations(id) ON DELETE CASCADE,state_hash TEXT UNIQUE NOT NULL,nonce TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS scim_tokens(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID UNIQUE NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),revoked BOOLEAN NOT NULL DEFAULT false)`);
  await q(`CREATE TABLE IF NOT EXISTS integrations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,type TEXT NOT NULL,name TEXT NOT NULL,base_url TEXT,secret_enc TEXT,config JSONB NOT NULL DEFAULT '{}'::jsonb,enabled BOOLEAN NOT NULL DEFAULT true,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS webhook_deliveries(id BIGSERIAL PRIMARY KEY,org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,workflow_id UUID REFERENCES workflows(id) ON DELETE SET NULL,event_type TEXT NOT NULL,endpoint TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,signature TEXT,status TEXT NOT NULL DEFAULT 'queued',attempts INT NOT NULL DEFAULT 0,next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),delivered_at TIMESTAMPTZ)`);
  await q(`CREATE TABLE IF NOT EXISTS extraction_schemas(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name TEXT NOT NULL,document_type TEXT NOT NULL,definition JSONB NOT NULL DEFAULT '{}'::jsonb,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(org_id,name))`);
  await q(`ALTER TABLE documents ADD COLUMN IF NOT EXISTS validation_status TEXT NOT NULL DEFAULT 'unknown', ADD COLUMN IF NOT EXISTS validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS extraction_mode TEXT`);
  await q(`ALTER TABLE approvals ADD COLUMN IF NOT EXISTS workflow_id UUID REFERENCES workflows(id) ON DELETE SET NULL`);
  await q(`CREATE TABLE IF NOT EXISTS document_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,version INT NOT NULL,changed_by UUID REFERENCES users(id) ON DELETE SET NULL,extracted_data JSONB NOT NULL DEFAULT '{}'::jsonb,change_note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(document_id,version))`);
  await q(`CREATE TABLE IF NOT EXISTS billing_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),provider TEXT NOT NULL,event_id TEXT NOT NULL UNIQUE,event_type TEXT,org_id UUID REFERENCES organizations(id) ON DELETE SET NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE TABLE IF NOT EXISTS sso_codes(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,code_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await q(`CREATE INDEX IF NOT EXISTS idx_sso_codes_expiry ON sso_codes(expires_at)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_versions_doc_created ON document_versions(document_id,created_at DESC)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_documents_org_created ON documents(org_id,created_at DESC)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_documents_org_status ON documents(org_id,status)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_audit_org_created ON audit_logs(org_id,created_at DESC)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_jobs_available ON job_queue(status,available_at)`);
  await q(`CREATE INDEX IF NOT EXISTS idx_webhook_next ON webhook_deliveries(status,next_attempt_at)`);
}

async function auth(req,res,next){
  try {
    const header=req.headers.authorization||''; const token=header.startsWith('Bearer ')?header.slice(7):null; if(!token) return res.status(401).json({error:'Authentication required'});
    if(token.startsWith('df_live_')) {
      const row=(await q(`SELECT k.*,o.name org_name,o.slug FROM api_keys k JOIN organizations o ON o.id=k.org_id WHERE k.key_hash=$1 AND k.revoked=false`,[hash(token)])).rows[0];
      if(!row) return res.status(401).json({error:'Invalid API key'});
      req.apiKey=row; req.user={id:row.created_by,org_id:row.org_id,email:'api',full_name:'API key',role:'api',org_name:row.org_name}; q('UPDATE api_keys SET last_used_at=NOW() WHERE id=$1',[row.id]).catch(()=>{}); return next();
    }
    const decoded=jwt.verify(token,JWT_SECRET); const row=(await q(`SELECT u.id,u.org_id,u.email,u.full_name,u.role,u.status,u.token_version,o.name org_name,o.slug,o.plan,o.trial_ends_at FROM users u JOIN organizations o ON o.id=u.org_id WHERE u.id=$1`,[decoded.sub])).rows[0];
    if(!row||row.status!=='active'||Number(row.token_version)!==Number(decoded.tokenVersion)) return res.status(401).json({error:'Session expired'});
    req.user=row; next();
  } catch(e) { return res.status(401).json({error:'Invalid authentication token'}); }
}
const roleWeight={viewer:1,member:2,admin:3,owner:4,api:2};
function requireRole(minRole){return(req,res,next)=>{if((roleWeight[req.user.role]||0)<roleWeight[minRole])return res.status(403).json({error:'Insufficient permission'});next();};}
function requireScope(scope){return(req,res,next)=>{if(!req.apiKey)return next();const scopes=Array.isArray(req.apiKey.scopes)?req.apiKey.scopes:[];if(!scopes.includes(scope))return res.status(403).json({error:`API key missing scope ${scope}`});next();};}

async function createJob(orgId,type,payload,maxAttempts=5){const r=await q(`INSERT INTO job_queue(org_id,type,payload,max_attempts) VALUES($1,$2,$3,$4) RETURNING id`,[orgId,type,payload,maxAttempts]);return r.rows[0].id;}
async function processDocument(doc) {
  let parsed; try { parsed=await parseStoredDocument(doc); } catch(e) { throw e; }
  const text=parsed.text||''; if(!text){await q(`UPDATE documents SET status='needs_ocr',error_message=$2 WHERE id=$1`,[doc.id,parsed.note||'Text could not be extracted']); return;}
  const guessed=/invoice|tax invoice/i.test(text)?'invoice':/contract|agreement/i.test(text)?'contract':/receipt/i.test(text)?'receipt':/purchase order|purchase order/i.test(text)?'purchase_order':'business_document';
  const type=doc.document_type==='unknown'?guessed:doc.document_type;
  const schema=(await q(`SELECT definition FROM extraction_schemas WHERE org_id=$1 AND document_type=$2 ORDER BY updated_at DESC LIMIT 1`,[doc.org_id,type])).rows[0]?.definition||null;
  const ai=await aiExtract(text,type,schema); const risk=riskFor(ai.data); const validation=validateExtraction(type,ai.data); const settings=(await q('SELECT * FROM organization_settings WHERE org_id=$1',[doc.org_id])).rows[0];
  const finalStatus = (validation.status==='needs_review' || risk==='high') ? 'needs_review' : 'processed';
  await q(`UPDATE documents SET status=$2,document_type=$3,extracted_text=$4,extracted_data=$5,confidence=$6,risk_level=$7,error_message=$8,pages=$9,validation_status=$10,validation_errors=$11,extraction_mode=$12,processed_at=NOW() WHERE id=$1`,[doc.id,finalStatus,type,text.slice(0,100000),ai.data,ai.confidence, risk, ai.error||null, parsed.pages||null, validation.status, validation.errors, ai.mode]);
  await q(`INSERT INTO usage_events(org_id,event_type,document_id,units,metadata) VALUES($1,$2,$3,1,$4)`,[doc.org_id,`document.processed.${ai.mode}`,doc.id,{mode:ai.mode,risk}]);
  const updated=(await q('SELECT * FROM documents WHERE id=$1',[doc.id])).rows[0];
  const workflowApprovals=await runWorkflows(updated.org_id,updated,updated.uploaded_by,settings);
  if(settings?.require_approval_for_high_risk&&(risk==='high'||validation.status==='needs_review')&&workflowApprovals===0) await q(`INSERT INTO approvals(org_id,document_id,requested_by,approver_role,note) VALUES($1,$2,$3,'admin',$4)`,[doc.org_id,doc.id,doc.uploaded_by,risk==='high'?'High-risk document requires review':'Extraction validation requires review']);
}
async function parseStoredDocument(doc){
  let temp; if(doc.storage_mode==='local') temp=doc.storage_key; else { const got=await storageGet(doc.storage_key); const out=path.join(UPLOAD_DIR,`work-${crypto.randomUUID()}`); const ws=fs.createWriteStream(out); await new Promise((resolve,reject)=>{got.stream.pipe(ws);got.stream.on('error',reject);ws.on('finish',resolve);ws.on('error',reject)}); temp=out; }
  try{return await parseDocument(temp,doc.mime_type);} finally {if(doc.storage_mode==='s3'){try{fs.unlinkSync(temp);}catch(_){}}}
}
async function deliverWebhook(row){
  const secret=decrypt((await q('SELECT definition->>\'webhook_secret\' secret FROM workflows WHERE id=$1',[row.workflow_id])).rows[0]?.secret)||process.env.WEBHOOK_SIGNING_SECRET||'';
  const body=JSON.stringify(row.payload); const signature=secret?`sha256=${crypto.createHmac('sha256',secret).update(body).digest('hex')}`:null;
  const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),Number(process.env.WEBHOOK_TIMEOUT_MS||10000));
  try{const r=await fetch(row.endpoint,{method:'POST',headers:{'content-type':'application/json','x-docflow-event':row.event_type,'x-docflow-delivery':String(row.id),...(signature?{'x-docflow-signature':signature}:{})},body,signal:controller.signal});if(!r.ok)throw new Error(`Webhook response ${r.status}`);await q(`UPDATE webhook_deliveries SET status='delivered',delivered_at=NOW(),attempts=attempts+1 WHERE id=$1`,[row.id]);return true;}catch(e){const attempts=Number(row.attempts||0)+1;const delay=Math.min(3600,Math.pow(2,attempts)*10);await q(`UPDATE webhook_deliveries SET status=$2,attempts=$3,last_error=$4,next_attempt_at=NOW()+($5 * INTERVAL '1 second') WHERE id=$1`,[row.id,attempts>=5?'failed':'queued',attempts,e.message,delay]);return false;}finally{clearTimeout(timer);}
}
async function runWorkflows(orgId,doc,actorUserId,settings){
  const rows=await q(`SELECT * FROM workflows WHERE org_id=$1 AND enabled=true AND trigger_type IN ('document_processed','document.processed')`,[orgId]);
  let approvalCount=0;
  for(const workflow of rows.rows){
    const run=(await q(`INSERT INTO workflow_runs(org_id,workflow_id,document_id,status,output) VALUES($1,$2,$3,'running',$4) RETURNING id`,[orgId,workflow.id,doc.id,{}])).rows[0];
    try{
      const def=workflow.definition||{}; if(def.document_type&&def.document_type!==doc.document_type){await q(`UPDATE workflow_runs SET status='skipped',finished_at=NOW() WHERE id=$1`,[run.id]);continue;}
      let approvalRequested=false; const needsPolicyApproval=!!(settings?.require_approval_for_high_risk && doc.status==='needs_review'); if(def.require_approval||needsPolicyApproval){const approverRole=(def.require_approval&&def.require_approval.role)||'admin';await q(`INSERT INTO approvals(org_id,document_id,requested_by,approver_role,workflow_id,note) VALUES($1,$2,$3,$4,$5,$6)`,[orgId,doc.id,actorUserId,approverRole,workflow.id,def.require_approval?'Workflow approval required':'Policy approval required for review-risk document']);approvalRequested=true;approvalCount++;}
      let webhookQueued=false; if(def.webhook_url && !approvalRequested){await q(`INSERT INTO webhook_deliveries(org_id,workflow_id,event_type,endpoint,payload) VALUES($1,$2,'document.processed',$3,$4)`,[orgId,workflow.id,def.webhook_url,{workflow:workflow.name,document_id:doc.id,document_type:doc.document_type,extracted_data:doc.extracted_data}]);webhookQueued=true;}
      await q(`UPDATE workflow_runs SET status=$2,output=$3,finished_at=CASE WHEN $2='waiting_approval' THEN NULL ELSE NOW() END WHERE id=$1`,[run.id,approvalRequested?'waiting_approval':'completed',{approval_requested:approvalRequested,webhook_queued:webhookQueued}]);
    }catch(e){await q(`UPDATE workflow_runs SET status='failed',error_message=$2,finished_at=NOW() WHERE id=$1`,[run.id,e.message]);}
  }
  return approvalCount;
}
async function resumeWorkflowRun(runId, orgId, approved) {
  const run=(await q(`SELECT r.*,w.*,d.* FROM workflow_runs r JOIN workflows w ON w.id=r.workflow_id JOIN documents d ON d.id=r.document_id WHERE r.id=$1 AND r.org_id=$2`,[runId,orgId])).rows[0];
  if(!run) throw new Error('Workflow run not found');
  if(!approved) { await q(`UPDATE workflow_runs SET status='rejected',finished_at=NOW(),output=output||$2 WHERE id=$1`,[runId,{approval_decision:'rejected'}]); return; }
  const def=run.definition||{}; let webhookQueued=false;
  if(def.webhook_url){await q(`INSERT INTO webhook_deliveries(org_id,workflow_id,event_type,endpoint,payload) VALUES($1,$2,'document.approved',$3,$4)`,[orgId,run.workflow_id,def.webhook_url,{workflow:run.name,document_id:run.document_id,document_type:run.document_type,extracted_data:run.extracted_data}]);webhookQueued=true;}
  await q(`UPDATE workflow_runs SET status='completed',finished_at=NOW(),output=output||$2 WHERE id=$1`,[runId,{approval_decision:'approved',webhook_queued:webhookQueued}]);
}
async function workerLoop(){
  if(!pool)return;
  const workerId=`worker-${crypto.randomUUID()}`;
  try{
    const picked=await q(`WITH c AS (SELECT id FROM job_queue WHERE ((status='queued') OR (status='processing' AND locked_at<NOW()-INTERVAL '10 minutes')) AND available_at<=NOW() ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE job_queue j SET status='processing',locked_at=NOW(),locked_by=$1,attempts=attempts+1 FROM c WHERE j.id=c.id RETURNING j.*`,[workerId]);
    const job=picked.rows[0]; if(!job)return;
    try{
      if(job.type==='document.process'){const doc=(await q('SELECT * FROM documents WHERE id=$1 AND org_id=$2',[job.payload.documentId,job.org_id])).rows[0];if(doc)await processDocument(doc);}
      else if(job.type==='webhook.deliver'){const row=(await q('SELECT * FROM webhook_deliveries WHERE id=$1 AND org_id=$2',[job.payload.deliveryId,job.org_id])).rows[0];if(row)await deliverWebhook(row);}
      else if(job.type==='workflow.resume'){await resumeWorkflowRun(job.payload.runId,job.org_id,job.payload.approved===true);}
      await q(`UPDATE job_queue SET status='completed',finished_at=NOW(),locked_at=NULL WHERE id=$1`,[job.id]);
    }catch(e){const retry=Number(job.attempts)<Number(job.max_attempts);await q(`UPDATE job_queue SET status=$2,error_message=$3,available_at=NOW()+($4 * INTERVAL '1 second'),locked_at=NULL WHERE id=$1`,[job.id,retry?'queued':'failed',e.message,retry?Math.min(600,Number(job.attempts)*15):0]);}
  }catch(_){ }
}
setInterval(()=>workerLoop(),Number(process.env.WORKER_INTERVAL_MS||2000)).unref();
setInterval(async()=>{if(!pool)return;try{const rows=await q(`SELECT d.* FROM documents d JOIN organization_settings s ON s.org_id=d.org_id WHERE d.created_at<NOW()-(COALESCE(s.retention_days,365) * INTERVAL '1 day') LIMIT 100`);for(const doc of rows.rows){await storageDelete(doc.storage_key);await q('DELETE FROM documents WHERE id=$1',[doc.id]);await audit(doc.org_id,null,'document.retention_deleted','document',doc.id,{retention:true});}}catch(_){}} , 60*60*1000).unref();
setInterval(async()=>{if(!pool)return;try{const rows=await q(`SELECT id,org_id FROM webhook_deliveries WHERE status='queued' AND next_attempt_at<=NOW() ORDER BY id LIMIT 20`);for(const row of rows.rows){await createJob(row.org_id,'webhook.deliver',{deliveryId:row.id},5);await q(`UPDATE webhook_deliveries SET status='dispatching' WHERE id=$1 AND status='queued'`,[row.id]);}}catch(_){}} ,3000).unref();

app.get('/api/health', async (req,res)=>{let db='not-configured';if(pool){try{await q('SELECT 1');db='ok';}catch(_){db='error';}}res.json({ok:db!=='error',service:'docflow',version:VERSION,database:db,ai:!!process.env.AI_API_KEY,ocr:!!process.env.OCR_API_URL,storage:storageMode,queue:!!pool});});
app.get('/api/readiness', requireDb, async (_req,res)=>{const checks={database:false,encryption:!!ENCRYPTION_KEY,jwt:!!JWT_SECRET,storage:storageMode==='s3',smtp:!!process.env.SMTP_HOST,ai:!!process.env.AI_API_KEY,oidc:!!(process.env.OIDC_ISSUER_URL&&process.env.OIDC_CLIENT_ID&&process.env.OIDC_CLIENT_SECRET),scim:!!process.env.SCIM_TOKEN_SECRET,backups_configured:process.env.BACKUP_STATUS==='configured',monitoring:!!process.env.METRICS_TOKEN};try{await q('SELECT 1');checks.database=true;}catch(_){}const core=checks.database&&checks.encryption&&checks.jwt;res.status(core?200:503).json({ok:core,checks,notes:{storage:'Durable S3-compatible object storage should be used before sensitive production workloads',backups:'Database backups and restore tests remain an operator responsibility',compliance:'Formal certifications require organization-specific controls and independent assessment'}});});

app.post('/api/auth/register',authLimiter,requireDb,async(req,res,next)=>{try{const {workspaceName,fullName,email,password}=req.body||{};if(!workspaceName||!fullName||!email||!password||password.length<10)return res.status(400).json({error:'Workspace, name, email and a 10+ character password are required'});const base=slugify(workspaceName);let slug=base,i=1;while((await q('SELECT 1 FROM organizations WHERE slug=$1',[slug])).rowCount)slug=`${base}-${i++}`;const trialDays=Number(process.env.TRIAL_DAYS||14);const org=(await q(`INSERT INTO organizations(name,slug,trial_ends_at) VALUES($1,$2,NOW()+($3 * INTERVAL '1 day')) RETURNING *`,[workspaceName,slug,trialDays])).rows[0];await q(`INSERT INTO organization_settings(org_id) VALUES($1)`,[org.id]);const passwordHash=await bcrypt.hash(password,12);const user=(await q(`INSERT INTO users(org_id,email,password_hash,full_name,role) VALUES($1,$2,$3,$4,'owner') RETURNING id,org_id,email,full_name,role,token_version`,[org.id,email.toLowerCase().trim(),passwordHash,fullName.trim()])).rows[0];await audit(org.id,user.id,'workspace.created','organization',org.id,{name:workspaceName});res.status(201).json({token:signToken(user),user:{...user,org_name:org.name},org:{id:org.id,name:org.name,slug:org.slug,plan:org.plan,trial_ends_at:org.trial_ends_at}});}catch(e){next(e);}});
app.post('/api/auth/login',authLimiter,requireDb,async(req,res,next)=>{try{const {email,password,workspace,mfaCode}=req.body||{};if(!email||!password)return res.status(400).json({error:'Email and password are required'});let sql=`SELECT u.id,u.org_id,u.email,u.password_hash,u.full_name,u.role,u.status,u.token_version,o.name org_name,o.slug,o.plan,o.trial_ends_at FROM users u JOIN organizations o ON o.id=u.org_id WHERE lower(u.email)=lower($1)`;const params=[email.trim()];if(workspace){sql+=' AND lower(o.slug)=lower($2)';params.push(slugify(workspace));}sql+=' LIMIT 1';const row=(await q(sql,params)).rows[0];if(!row||!(await bcrypt.compare(password,row.password_hash)))return res.status(401).json({error:'Invalid credentials'});const method=(await q('SELECT * FROM mfa_methods WHERE user_id=$1 AND enabled=true',[row.id])).rows[0];if(method&&!mfaCode)return res.status(200).json({mfa_required:true});if(method&&!totpVerify(decrypt(method.secret_enc),mfaCode))return res.status(401).json({error:'Invalid MFA code'});await audit(row.org_id,row.id,'auth.login','user',row.id);res.json({token:signToken(row),user:{id:row.id,org_id:row.org_id,email:row.email,full_name:row.full_name,role:row.role,org_name:row.org_name},org:{id:row.org_id,name:row.org_name,slug:row.slug,plan:row.plan,trial_ends_at:row.trial_ends_at}});}catch(e){next(e);}});
app.post('/api/auth/password-reset/request',authLimiter,requireDb,async(req,res,next)=>{try{const email=String(req.body?.email||'').trim().toLowerCase();const row=(await q('SELECT id,org_id FROM users WHERE lower(email)=lower($1) LIMIT 1',[email])).rows[0];if(row){const raw=randomToken(24);await q(`INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')`,[row.id,hash(raw)]);const link=`${process.env.APP_BASE_URL||'http://localhost:3000'}/?reset=${raw}`;await sendMail(email,'DocFlow password reset',`Reset your DocFlow password: ${link}`);await audit(row.org_id,row.id,'auth.password_reset_requested','user',row.id);}res.json({ok:true});}catch(e){next(e);}});
app.post('/api/auth/password-reset/complete',requireDb,async(req,res,next)=>{try{const {token,password}=req.body||{};if(!token||!password||password.length<10)return res.status(400).json({error:'Reset token and 10+ character password required'});const row=(await q(`SELECT * FROM password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()`,[hash(token)])).rows[0];if(!row)return res.status(400).json({error:'Reset token is invalid or expired'});await q('UPDATE users SET password_hash=$1,token_version=token_version+1 WHERE id=$2',[await bcrypt.hash(password,12),row.user_id]);await q('UPDATE password_resets SET used_at=NOW() WHERE id=$1',[row.id]);res.json({ok:true});}catch(e){next(e);}});

async function enforceTrial(orgId){const row=(await q('SELECT plan,trial_ends_at FROM organizations WHERE id=$1',[orgId])).rows[0];if(!row)return; if(row.plan==='trial'&&row.trial_ends_at&&new Date(row.trial_ends_at)<new Date()) throw Object.assign(new Error('Trial period has ended. Please upgrade your workspace.'),{statusCode:402});}
app.get('/api/me',requireDb,auth,async(req,res,next)=>{try{const org=(await q('SELECT * FROM organizations WHERE id=$1',[req.user.org_id])).rows[0];const stats=(await q(`SELECT COUNT(*)::int documents,COUNT(*) FILTER(WHERE status='processed')::int processed,COUNT(*) FILTER(WHERE status='needs_ocr')::int needs_ocr,COUNT(*) FILTER(WHERE risk_level='high')::int high_risk FROM documents WHERE org_id=$1`,[req.user.org_id])).rows[0];const pending=(await q(`SELECT COUNT(*)::int count FROM approvals WHERE org_id=$1 AND status='pending'`,[req.user.org_id])).rows[0].count;const set=(await q('SELECT * FROM organization_settings WHERE org_id=$1',[req.user.org_id])).rows[0];res.json({user:req.user,org,stats:{...stats,pending_approvals:pending},settings:set});}catch(e){next(e);}});
app.get('/api/dashboard',requireDb,auth,async(req,res,next)=>{try{const [doc,appv,runs,trend,u]=await Promise.all([q(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='processed')::int processed,COUNT(*) FILTER(WHERE status='needs_ocr')::int needs_ocr,COUNT(*) FILTER(WHERE status='failed')::int failed,COUNT(*) FILTER(WHERE risk_level='high')::int high_risk FROM documents WHERE org_id=$1`,[req.user.org_id]),q(`SELECT COUNT(*)::int pending FROM approvals WHERE org_id=$1 AND status='pending'`,[req.user.org_id]),q(`SELECT COUNT(*)::int active FROM workflow_runs WHERE org_id=$1 AND created_at>NOW()-INTERVAL '24 hours' AND status='running'`,[req.user.org_id]),q(`SELECT DATE(created_at) AS day,COUNT(*)::int count FROM documents WHERE org_id=$1 AND created_at>NOW()-INTERVAL '14 days' GROUP BY 1 ORDER BY 1`,[req.user.org_id]),usage(req.user.org_id)]);res.json({documents:doc.rows[0],approvals:appv.rows[0],runs:runs.rows[0],trend:trend.rows,usage:u});}catch(e){next(e);}});

app.get('/api/documents',requireDb,auth,requireScope('documents:read'),async(req,res,next)=>{try{const limit=Math.min(Number(req.query.limit||50),200);const params=[req.user.org_id];let where='WHERE org_id=$1';if(req.query.status){params.push(req.query.status);where+=` AND status=$${params.length}`;}if(req.query.type){params.push(req.query.type);where+=` AND document_type=$${params.length}`;}if(req.query.q){params.push(`%${String(req.query.q).slice(0,80)}%`);where+=` AND original_name ILIKE $${params.length}`;}params.push(limit);const rows=await q(`SELECT id,name,original_name,mime_type,size_bytes,status,document_type,confidence,risk_level,error_message,pages,validation_status,validation_errors,extraction_mode,created_at,processed_at,extracted_data FROM documents ${where} ORDER BY created_at DESC LIMIT $${params.length}`,params);res.json({documents:rows.rows});}catch(e){next(e);}});
app.post('/api/documents/upload',uploadLimiter,requireDb,auth,requireRole('member'),requireScope('documents:write'),upload.array('files',MAX_BATCH),async(req,res,next)=>{const created=[];try{await enforceTrial(req.user.org_id);if(!req.files?.length)return res.status(400).json({error:'No supported files uploaded'});for(const file of req.files){if(!fileMagicValid(file)){try{fs.unlinkSync(file.path)}catch(_){ }throw Object.assign(new Error('File content does not match its declared type'),{statusCode:400});}await enforceUsage(req.user.org_id,file.size);const digest=hash(fs.readFileSync(file.path));const objectKey=`${req.user.org_id}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${sanitizeFilename(file.originalname)}`;const stored=await storagePut(file.path,objectKey,file.mimetype);if(storageMode==='s3')try{fs.unlinkSync(file.path)}catch(_){}const row=(await q(`INSERT INTO documents(org_id,uploaded_by,name,original_name,mime_type,size_bytes,storage_key,storage_mode,sha256,checksum,status,document_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,'queued',$10) RETURNING id,original_name,status`,[req.user.org_id,req.user.id,file.filename,sanitizeFilename(file.originalname),file.mimetype,file.size,stored.key,stored.mode,digest,req.body.documentType||'unknown'])).rows[0];await audit(req.user.org_id,req.user.id,'document.uploaded','document',row.id,{name:row.original_name,size_bytes:file.size,sha256:digest});await createJob(req.user.org_id,'document.process',{documentId:row.id});created.push(row);}res.status(201).json({documents:created});}catch(e){for(const file of req.files||[]){try{if(storageMode==='local')fs.unlinkSync(file.path)}catch(_){}}next(e);}});
app.get('/api/documents/:id',requireDb,auth,requireScope('documents:read'),async(req,res,next)=>{try{const row=(await q('SELECT * FROM documents WHERE id=$1 AND org_id=$2',[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Document not found'});res.json({document:row});}catch(e){next(e);}});
app.get('/api/documents/:id/download',requireDb,auth,requireScope('documents:read'),async(req,res,next)=>{try{const row=(await q('SELECT * FROM documents WHERE id=$1 AND org_id=$2',[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Document not found'});const got=await storageGet(row.storage_key);res.setHeader('Content-Type',got.contentType||row.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(row.original_name)}`);got.stream.pipe(res);}catch(e){next(e);}});
app.delete('/api/documents/:id',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const row=(await q('DELETE FROM documents WHERE id=$1 AND org_id=$2 RETURNING *',[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Document not found'});await storageDelete(row.storage_key);await audit(req.user.org_id,req.user.id,'document.deleted','document',row.id,{original_name:row.original_name});res.json({ok:true});}catch(e){next(e);}});
app.get('/api/export/documents.csv',requireDb,auth,requireRole('admin'),requireScope('exports:read'),async(req,res,next)=>{try{const rows=(await q(`SELECT original_name,document_type,status,confidence,risk_level,pages,created_at,processed_at,extracted_data FROM documents WHERE org_id=$1 ORDER BY created_at DESC`,[req.user.org_id])).rows;const csv=[['original_name','document_type','status','confidence','risk_level','pages','created_at','processed_at','extracted_data'].join(','),...rows.map(r=>[r.original_name,r.document_type,r.status,r.confidence,r.risk_level,r.pages,r.created_at?.toISOString?.()||r.created_at,r.processed_at?.toISOString?.()||r.processed_at,JSON.stringify(r.extracted_data)].map(csvEscape).join(','))].join('\n');res.setHeader('content-type','text/csv; charset=utf-8');res.setHeader('content-disposition','attachment; filename="docflow-documents.csv"');res.send(csv);}catch(e){next(e);}});

app.get('/api/approvals',requireDb,auth,requireScope('approvals:read'),async(req,res,next)=>{try{const rows=await q(`SELECT a.*,d.original_name,d.document_type,d.extracted_data,u.full_name requested_by_name FROM approvals a JOIN documents d ON d.id=a.document_id LEFT JOIN users u ON u.id=a.requested_by WHERE a.org_id=$1 ORDER BY a.created_at DESC LIMIT 200`,[req.user.org_id]);res.json({approvals:rows.rows});}catch(e){next(e);}});
app.post('/api/approvals/:id/decision',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const status=req.body?.status;if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Decision must be approved or rejected'});const existing=(await q("SELECT * FROM approvals WHERE id=$1 AND org_id=$2 AND status='pending'",[req.params.id,req.user.org_id])).rows[0];if(!existing)return res.status(404).json({error:'Approval not found or already decided'});if(existing.approver_role==='owner'&&req.user.role!=='owner')return res.status(403).json({error:'Owner approval is required'});const row=(await q(`UPDATE approvals SET status=$1,decided_by=$2,decided_at=NOW(),note=$3 WHERE id=$4 AND org_id=$5 AND status='pending' RETURNING *`,[status,req.user.id,req.body.note||null,req.params.id,req.user.org_id])).rows[0];await audit(req.user.org_id,req.user.id,`approval.${status}`,'approval',row.id,{document_id:row.document_id,note:req.body.note||null});if(row.workflow_id){const run=(await q(`SELECT id FROM workflow_runs WHERE workflow_id=$1 AND document_id=$2 AND org_id=$3 AND status='waiting_approval' ORDER BY created_at DESC LIMIT 1`,[row.workflow_id,row.document_id,req.user.org_id])).rows[0];if(run)await createJob(req.user.org_id,'workflow.resume',{runId:run.id,approved:status==='approved'});}res.json({approval:row});}catch(e){next(e);}});

app.get('/api/workflows',requireDb,auth,requireScope('workflows:read'),async(req,res,next)=>{try{const rows=await q('SELECT * FROM workflows WHERE org_id=$1 ORDER BY created_at DESC',[req.user.org_id]);res.json({workflows:rows.rows});}catch(e){next(e);}});
app.post('/api/workflows',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const {name,description,triggerType,definition,enabled}=req.body||{};if(!name||!triggerType)return res.status(400).json({error:'Name and trigger type are required'});if(!['document_processed','document.processed'].includes(triggerType))return res.status(400).json({error:'Unsupported trigger type'});const safeDef=jsonSafe(definition||{});if(safeDef.webhook_url)safeDef.webhook_url=validateWebhookUrl(safeDef.webhook_url);if(safeDef.webhook_secret)safeDef.webhook_secret=encrypt(safeDef.webhook_secret);const row=(await q(`INSERT INTO workflows(org_id,name,description,trigger_type,definition,enabled,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.user.org_id,String(name).slice(0,120),description||null,triggerType,safeDef,enabled!==false,req.user.id])).rows[0];await audit(req.user.org_id,req.user.id,'workflow.created','workflow',row.id,{name});res.status(201).json({workflow:row});}catch(e){next(e);}});
app.patch('/api/workflows/:id',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const def=req.body.definition?jsonSafe(req.body.definition):null;if(def?.webhook_url)def.webhook_url=validateWebhookUrl(def.webhook_url);if(def?.webhook_secret)def.webhook_secret=encrypt(def.webhook_secret);const row=(await q(`UPDATE workflows SET name=COALESCE($1,name),description=COALESCE($2,description),enabled=COALESCE($3,enabled),definition=COALESCE($4,definition),updated_at=NOW() WHERE id=$5 AND org_id=$6 RETURNING *`,[req.body.name||null,req.body.description||null,typeof req.body.enabled==='boolean'?req.body.enabled:null,def,req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Workflow not found'});await audit(req.user.org_id,req.user.id,'workflow.updated','workflow',row.id);res.json({workflow:row});}catch(e){next(e);}});
app.delete('/api/workflows/:id',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const r=await q('DELETE FROM workflows WHERE id=$1 AND org_id=$2 RETURNING id',[req.params.id,req.user.org_id]);if(!r.rowCount)return res.status(404).json({error:'Workflow not found'});await audit(req.user.org_id,req.user.id,'workflow.deleted','workflow',req.params.id);res.json({ok:true});}catch(e){next(e);}});
app.get('/api/workflow-runs',requireDb,auth,requireRole('member'),requireScope('workflows:read'),async(req,res,next)=>{try{const rows=await q(`SELECT r.*,w.name workflow_name,d.original_name FROM workflow_runs r LEFT JOIN workflows w ON w.id=r.workflow_id LEFT JOIN documents d ON d.id=r.document_id WHERE r.org_id=$1 ORDER BY r.created_at DESC LIMIT 200`,[req.user.org_id]);res.json({runs:rows.rows});}catch(e){next(e);}});

app.get('/api/team',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const [users,invites]=await Promise.all([q(`SELECT id,email,full_name,role,status,created_at FROM users WHERE org_id=$1 ORDER BY created_at`,[req.user.org_id]),q(`SELECT id,email,role,status,expires_at,created_at FROM invites WHERE org_id=$1 ORDER BY created_at DESC LIMIT 100`,[req.user.org_id])]);res.json({users:users.rows,invites:invites.rows});}catch(e){next(e);}});
app.post('/api/team/invites',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const email=String(req.body?.email||'').trim().toLowerCase();const role=['viewer','member','admin'].includes(req.body?.role)?req.body.role:'member';if(!email)return res.status(400).json({error:'Invite email required'});const raw=randomToken(24);const invite=(await q(`INSERT INTO invites(org_id,email,role,token_hash,expires_at,invited_by) VALUES($1,$2,$3,$4,NOW()+INTERVAL '7 days',$5) RETURNING id,email,role,expires_at`,[req.user.org_id,email,role,hash(raw),req.user.id])).rows[0];const link=`${process.env.APP_BASE_URL||'http://localhost:3000'}/?invite=${raw}`;await sendMail(email,`Invitation to ${req.user.org_name} on ${APP_NAME}`,`You have been invited to ${req.user.org_name}. Accept: ${link}`);await audit(req.user.org_id,req.user.id,'team.invite_created','invite',invite.id,{email,role});res.status(201).json({invite,acceptToken:raw});}catch(e){next(e);}});
app.post('/api/team/invites/accept',requireDb,async(req,res,next)=>{try{const {token,fullName,password}=req.body||{};if(!token||!fullName||!password||password.length<10)return res.status(400).json({error:'Invitation, name and 10+ character password are required'});const inv=(await q(`SELECT * FROM invites WHERE token_hash=$1 AND status='pending' AND expires_at>NOW()`,[hash(token)])).rows[0];if(!inv)return res.status(400).json({error:'Invitation is invalid or expired'});const exists=await q('SELECT id FROM users WHERE org_id=$1 AND lower(email)=lower($2)',[inv.org_id,inv.email]);if(exists.rowCount)return res.status(409).json({error:'An account already exists for this email'});const user=(await q(`INSERT INTO users(org_id,email,password_hash,full_name,role) VALUES($1,$2,$3,$4,$5) RETURNING id,org_id,email,full_name,role,token_version`,[inv.org_id,inv.email,await bcrypt.hash(password,12),fullName.trim(),inv.role])).rows[0];await q(`UPDATE invites SET status='accepted' WHERE id=$1`,[inv.id]);await audit(inv.org_id,user.id,'team.invite_accepted','invite',inv.id,{email:user.email});const org=(await q('SELECT * FROM organizations WHERE id=$1',[inv.org_id])).rows[0];res.status(201).json({token:signToken(user),user:{...user,org_name:org.name},org});}catch(e){next(e);}});
app.patch('/api/team/users/:id',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const target=(await q('SELECT id,role,status FROM users WHERE id=$1 AND org_id=$2',[req.params.id,req.user.org_id])).rows[0];if(!target)return res.status(404).json({error:'User not found'});if(target.role==='owner'&&req.user.role!=='owner')return res.status(403).json({error:'Only the workspace owner can modify the owner account'});if(req.params.id===req.user.id&&req.body?.status==='suspended')return res.status(400).json({error:'You cannot suspend your own account'});if(req.body?.role==='owner')return res.status(400).json({error:'Owner transfer is not supported through this endpoint'});const role=['viewer','member','admin'].includes(req.body?.role)?req.body.role:null;const status=['active','suspended'].includes(req.body?.status)?req.body.status:null;const row=(await q(`UPDATE users SET role=COALESCE($1,role),status=COALESCE($2,status),token_version=CASE WHEN $2='suspended' THEN token_version+1 ELSE token_version END WHERE id=$3 AND org_id=$4 RETURNING id,email,full_name,role,status`,[role,status,req.params.id,req.user.org_id])).rows[0];await audit(req.user.org_id,req.user.id,'team.user_updated','user',row.id,{role,status});res.json({user:row});}catch(e){next(e);}});

app.get('/api/security/settings',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const set=(await q('SELECT * FROM organization_settings WHERE org_id=$1',[req.user.org_id])).rows[0];const mfa=(await q('SELECT enabled FROM mfa_methods WHERE user_id=$1',[req.user.id])).rows[0];const readiness={s3:storageMode==='s3',encryption:!!ENCRYPTION_KEY,oidc:!!(process.env.OIDC_ISSUER_URL&&process.env.OIDC_CLIENT_ID&&process.env.OIDC_CLIENT_SECRET),scim:!!process.env.SCIM_TOKEN_SECRET,smtp:!!process.env.SMTP_HOST};res.json({settings:set,mfa_enabled:!!mfa?.enabled,readiness});}catch(e){next(e);}});
app.patch('/api/security/settings',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const retention=Math.max(30,Math.min(3650,Number(req.body?.retention_days||365)));const reqApproval=typeof req.body?.require_approval_for_high_risk==='boolean'?req.body.require_approval_for_high_risk:true;await q(`UPDATE organization_settings SET retention_days=$1,require_approval_for_high_risk=$2,updated_at=NOW() WHERE org_id=$3`,[retention,reqApproval,req.user.org_id]);await audit(req.user.org_id,req.user.id,'security.settings_updated','organization',req.user.org_id,{retention_days:retention,require_approval_for_high_risk:reqApproval});res.json({ok:true});}catch(e){next(e);}});
app.post('/api/security/mfa/setup',requireDb,auth,async(req,res,next)=>{try{const secret=base32Encode(crypto.randomBytes(20));await q(`INSERT INTO mfa_methods(user_id,secret_enc,enabled) VALUES($1,$2,false) ON CONFLICT(user_id) DO UPDATE SET secret_enc=EXCLUDED.secret_enc,enabled=false`,[req.user.id,encrypt(secret)]);const issuer=encodeURIComponent(APP_NAME);const account=encodeURIComponent(req.user.email);res.json({secret,otpauth:`otpauth://totp/${issuer}:${account}?secret=${secret}&issuer=${issuer}`});}catch(e){next(e);}});
app.post('/api/security/mfa/confirm',requireDb,auth,async(req,res,next)=>{try{const row=(await q('SELECT * FROM mfa_methods WHERE user_id=$1',[req.user.id])).rows[0];if(!row)return res.status(404).json({error:'MFA setup not started'});if(!totpVerify(decrypt(row.secret_enc),req.body?.code))return res.status(400).json({error:'Invalid authenticator code'});await q('UPDATE mfa_methods SET enabled=true WHERE user_id=$1',[req.user.id]);await audit(req.user.org_id,req.user.id,'security.mfa_enabled','user',req.user.id);res.json({ok:true});}catch(e){next(e);}});
app.post('/api/security/mfa/disable',requireDb,auth,async(req,res,next)=>{try{await q('DELETE FROM mfa_methods WHERE user_id=$1',[req.user.id]);await audit(req.user.org_id,req.user.id,'security.mfa_disabled','user',req.user.id);res.json({ok:true});}catch(e){next(e);}});

app.get('/api/api-keys',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const rows=await q(`SELECT id,name,key_prefix,revoked,scopes,last_used_at,created_at FROM api_keys WHERE org_id=$1 ORDER BY created_at DESC`,[req.user.org_id]);res.json({keys:rows.rows});}catch(e){next(e);}});
app.post('/api/api-keys',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'Key name required'});const key=apiKeyMake();const requested=Array.isArray(req.body?.scopes)?req.body.scopes:['documents:read','documents:write'];const scopes=normalizeScopes(requested);if(!scopes.length)return res.status(400).json({error:'At least one valid scope is required'});const row=(await q(`INSERT INTO api_keys(org_id,name,key_prefix,key_hash,scopes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,key_prefix,scopes,created_at`,[req.user.org_id,name,key.prefix,key.digest,scopes,req.user.id])).rows[0];await audit(req.user.org_id,req.user.id,'api_key.created','api_key',row.id,{name,scopes});res.status(201).json({key:key.raw,apiKey:row,warning:'Copy this key now. It will not be shown again.'});}catch(e){next(e);}});
app.post('/api/api-keys/:id/revoke',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const row=(await q(`UPDATE api_keys SET revoked=true WHERE id=$1 AND org_id=$2 RETURNING id`,[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'API key not found'});await audit(req.user.org_id,req.user.id,'api_key.revoked','api_key',row.id);res.json({ok:true});}catch(e){next(e);}});

app.get('/api/integrations',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const rows=await q(`SELECT id,type,name,base_url,enabled,config,created_at FROM integrations WHERE org_id=$1 ORDER BY created_at DESC`,[req.user.org_id]);res.json({integrations:rows.rows});}catch(e){next(e);}});
app.post('/api/integrations',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const {type,name,baseUrl,secret,config}=req.body||{};if(!type||!name)return res.status(400).json({error:'Type and name required'});const row=(await q(`INSERT INTO integrations(org_id,type,name,base_url,secret_enc,config,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,type,name,base_url,enabled,config,created_at`,[req.user.org_id,type,name,baseUrl||null,secret?encrypt(secret):null,config||{},req.user.id])).rows[0];await audit(req.user.org_id,req.user.id,'integration.created','integration',row.id,{type,name});res.status(201).json({integration:row});}catch(e){next(e);}});
app.delete('/api/integrations/:id',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const r=await q('DELETE FROM integrations WHERE id=$1 AND org_id=$2 RETURNING id',[req.params.id,req.user.org_id]);if(!r.rowCount)return res.status(404).json({error:'Integration not found'});await audit(req.user.org_id,req.user.id,'integration.deleted','integration',req.params.id);res.json({ok:true});}catch(e){next(e);}});

app.get('/api/schemas',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const rows=await q('SELECT id,name,document_type,definition,created_at,updated_at FROM extraction_schemas WHERE org_id=$1 ORDER BY name',[req.user.org_id]);res.json({schemas:rows.rows});}catch(e){next(e);}});
app.post('/api/schemas',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const {name,documentType,definition}=req.body||{};if(!name||!documentType)return res.status(400).json({error:'Schema name and document type are required'});const row=(await q(`INSERT INTO extraction_schemas(org_id,name,document_type,definition,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(org_id,name) DO UPDATE SET document_type=EXCLUDED.document_type,definition=EXCLUDED.definition,updated_at=NOW() RETURNING *`,[req.user.org_id,name,documentType,definition||{},req.user.id])).rows[0];await audit(req.user.org_id,req.user.id,'schema.saved','extraction_schema',row.id,{name,document_type:documentType});res.status(201).json({schema:row});}catch(e){next(e);}});

app.get('/api/audit',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const rows=await q(`SELECT a.*,u.email FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.org_id=$1 ORDER BY a.created_at DESC LIMIT 500`,[req.user.org_id]);res.json({logs:rows.rows});}catch(e){next(e);}});
app.get('/api/enterprise/readiness',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const controls={tenant_isolation:true,rbac:true,audit:true,approval_gates:true,jwt_sessions:true,rate_limiting:true,security_headers:true,encrypted_secrets:!!ENCRYPTION_KEY,durable_object_storage:storageMode==='s3',oidc_sso:!!(process.env.OIDC_ISSUER_URL&&process.env.OIDC_CLIENT_ID&&process.env.OIDC_CLIENT_SECRET),scim:!!process.env.SCIM_TOKEN_SECRET,document_validation:true,document_versions:true,usage_controls:true,backup_restore:'external',central_monitoring:'external',penetration_test:'external',formal_compliance:'external'};res.json({version:VERSION,controls});}catch(e){next(e);}});

app.post('/api/oidc/start',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{if(!process.env.OIDC_ISSUER_URL||!process.env.OIDC_CLIENT_ID||!process.env.OIDC_CLIENT_SECRET)return res.status(503).json({error:'OIDC is not configured'});const state=randomToken(24);const nonce=randomToken(24);await q('INSERT INTO oidc_states(org_id,state_hash,nonce) VALUES($1,$2,$3)',[req.user.org_id,hash(state),nonce]);const discovery=await (await fetch(`${process.env.OIDC_ISSUER_URL.replace(/\/$/,'')}/.well-known/openid-configuration`)).json();const redirect=process.env.OIDC_REDIRECT_URI||`${process.env.APP_BASE_URL||'http://localhost:3000'}/api/oidc/callback`;const url=new URL(discovery.authorization_endpoint);url.searchParams.set('client_id',process.env.OIDC_CLIENT_ID);url.searchParams.set('response_type','code');url.searchParams.set('scope','openid profile email');url.searchParams.set('redirect_uri',redirect);url.searchParams.set('state',state);url.searchParams.set('nonce',nonce);res.json({url:url.toString()});}catch(e){next(e);}});
app.post('/api/auth/sso/exchange',requireDb,async(req,res,next)=>{try{const code=String(req.body?.code||'');if(!code)return res.status(400).json({error:'SSO exchange code required'});const row=(await q('SELECT s.*,u.id user_id,u.org_id,u.email,u.full_name,u.role,u.token_version,o.name org_name,o.slug,o.plan,o.trial_ends_at FROM sso_codes s JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=s.org_id WHERE s.code_hash=$1 AND s.used_at IS NULL AND s.expires_at>NOW()',[hash(code)])).rows[0];if(!row)return res.status(401).json({error:'SSO code expired or invalid'});await q('UPDATE sso_codes SET used_at=NOW() WHERE id=$1',[row.id]);res.json({token:signToken(row,{sso:true}),user:{id:row.user_id,org_id:row.org_id,email:row.email,full_name:row.full_name,role:row.role,org_name:row.org_name},org:{id:row.org_id,name:row.org_name,slug:row.slug,plan:row.plan,trial_ends_at:row.trial_ends_at}});}catch(e){next(e);}});
app.post('/api/oidc/start-public',requireDb,async(req,res,next)=>{try{if(!process.env.OIDC_ISSUER_URL||!process.env.OIDC_CLIENT_ID||!process.env.OIDC_CLIENT_SECRET)return res.status(503).json({error:'OIDC is not configured'});const workspace=slugify(req.body?.workspace||'');if(!workspace)return res.status(400).json({error:'Workspace slug is required'});const org=(await q('SELECT id,slug FROM organizations WHERE lower(slug)=lower($1)',[workspace])).rows[0];if(!org)return res.status(404).json({error:'Workspace not found'});const state=randomToken(24);const nonce=randomToken(24);await q('INSERT INTO oidc_states(org_id,state_hash,nonce) VALUES($1,$2,$3)',[org.id,hash(state),nonce]);const discovery=await (await fetch(`${process.env.OIDC_ISSUER_URL.replace(/\/$/,'')}/.well-known/openid-configuration`)).json();const redirect=process.env.OIDC_REDIRECT_URI||`${process.env.APP_BASE_URL||'http://localhost:3000'}/api/oidc/callback`;const url=new URL(discovery.authorization_endpoint);url.searchParams.set('client_id',process.env.OIDC_CLIENT_ID);url.searchParams.set('response_type','code');url.searchParams.set('scope','openid profile email');url.searchParams.set('redirect_uri',redirect);url.searchParams.set('state',state);url.searchParams.set('nonce',nonce);res.json({url:url.toString()});}catch(e){next(e);}});
app.get('/api/oidc/callback',requireDb,async(req,res)=>{try{const row=(await q('SELECT * FROM oidc_states WHERE state_hash=$1 AND created_at>NOW()-INTERVAL \'10 minutes\'',[hash(req.query.state||'')])).rows[0];if(!row)return res.status(400).send('Invalid or expired SSO state');const discovery=await (await fetch(`${process.env.OIDC_ISSUER_URL.replace(/\/$/,'')}/.well-known/openid-configuration`)).json();const body=new URLSearchParams({grant_type:'authorization_code',code:String(req.query.code||''),redirect_uri:process.env.OIDC_REDIRECT_URI||`${process.env.APP_BASE_URL||'http://localhost:3000'}/api/oidc/callback`,client_id:process.env.OIDC_CLIENT_ID,client_secret:process.env.OIDC_CLIENT_SECRET});const tokenRes=await fetch(discovery.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const tokens=await tokenRes.json();if(!tokenRes.ok)throw new Error(tokens.error_description||'OIDC token exchange failed');const jwks=createRemoteJWKSet(new URL(discovery.jwks_uri));const verified=await jwtVerify(tokens.id_token,jwks,{issuer:process.env.OIDC_ISSUER_URL,audience:process.env.OIDC_CLIENT_ID});if(verified.payload.nonce!==row.nonce)throw new Error('OIDC nonce mismatch');const email=String(verified.payload.email||'').toLowerCase();if(!email)throw new Error('SSO account has no email claim');const orgSettings=(await q('SELECT allowed_email_domain FROM organization_settings WHERE org_id=$1',[row.org_id])).rows[0];if(orgSettings?.allowed_email_domain&&!email.endsWith('@'+String(orgSettings.allowed_email_domain).toLowerCase().replace(/^@/,'')))throw new Error('SSO email domain is not allowed for this workspace');const user=(await q('SELECT u.*,o.name org_name,o.slug,o.plan,o.trial_ends_at FROM users u JOIN organizations o ON o.id=u.org_id WHERE u.org_id=$1 AND lower(u.email)=lower($2)',[row.org_id,email])).rows[0];if(!user)throw new Error('SSO user is not provisioned in this workspace');await q('DELETE FROM oidc_states WHERE id=$1',[row.id]);const rawCode=randomToken(24);await q('INSERT INTO sso_codes(org_id,user_id,code_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \'2 minutes\')',[row.org_id,user.id,hash(rawCode)]);const token=rawCode;res.redirect(`${process.env.APP_BASE_URL||'http://localhost:3000'}/?sso_code=${encodeURIComponent(token)}`);}catch(e){res.status(400).send(`SSO sign-in failed: ${String(e.message).replace(/[<>]/g,'')}`);}});

function scimDigest(token){return process.env.SCIM_TOKEN_SECRET?crypto.createHmac('sha256',process.env.SCIM_TOKEN_SECRET).update(String(token)).digest('hex'):hash(token);}
async function scimOrg(req){const token=String((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!token||!process.env.SCIM_TOKEN_SECRET)return null;const row=(await q('SELECT s.*,o.slug FROM scim_tokens s JOIN organizations o ON o.id=s.org_id WHERE s.token_hash=$1 AND s.revoked=false',[scimDigest(token)])).rows[0];return row||null;}
app.post('/api/scim/token',requireDb,auth,requireRole('owner'),async(req,res,next)=>{try{const raw='scim_'+randomToken(32);await q(`INSERT INTO scim_tokens(org_id,token_hash,created_by) VALUES($1,$2,$3) ON CONFLICT(org_id) DO UPDATE SET token_hash=EXCLUDED.token_hash,created_by=EXCLUDED.created_by,created_at=NOW(),revoked=false`,[req.user.org_id,scimDigest(raw),req.user.id]);await audit(req.user.org_id,req.user.id,'scim.token_rotated','scim',req.user.org_id);res.json({token:raw,warning:'Copy this token now. It will not be shown again.'});}catch(e){next(e);}});
app.get('/scim/v2.0/:org/ServiceProviderConfig',requireDb,async(req,res)=>{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});res.json({schemas:['urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig'],patch:{supported:true},bulk:{supported:false},filter:{supported:true,maxResults:1000},changePassword:{supported:false},sort:{supported:true},etag:{supported:false},authenticationSchemes:[{type:'oauthbearertoken',name:'Bearer Token',description:'DocFlow SCIM bearer token'}]});});
app.get('/scim/v2.0/:org/ResourceTypes',requireDb,async(req,res)=>{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});res.json({schemas:['urn:ietf:params:scim:api:messages:2.0:ListResponse'],totalResults:1,startIndex:1,itemsPerPage:1,Resources:[{schemas:['urn:ietf:params:scim:schemas:core:2.0:ResourceType'],id:'User',name:'User',endpoint:'/Users',schema:'urn:ietf:params:scim:schemas:core:2.0:User'}]});});
app.get('/scim/v2.0/:org/Users',requireDb,async(req,res)=>{try{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});const rows=await q(`SELECT id,email,full_name,role,status FROM users WHERE org_id=$1 ORDER BY email LIMIT 1000`,[s.org_id]);res.json({schemas:['urn:ietf:params:scim:api:messages:2.0:ListResponse'],totalResults:rows.rowCount,startIndex:1,itemsPerPage:rows.rowCount,Resources:rows.rows.map(u=>({schemas:['urn:ietf:params:scim:schemas:core:2.0:User'],id:u.id,userName:u.email,displayName:u.full_name,active:u.status==='active'}))});}catch(e){res.status(500).json({error:e.message});}});
app.post('/scim/v2.0/:org/Users',requireDb,async(req,res)=>{try{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});const email=String(req.body?.userName||'').toLowerCase();const fullName=req.body?.displayName||email;const existing=(await q('SELECT id FROM users WHERE org_id=$1 AND lower(email)=lower($2)',[s.org_id,email])).rows[0];if(existing)return res.status(409).json({detail:'User already exists'});const temp=randomToken(12)+'A!';const role='member';const user=(await q(`INSERT INTO users(org_id,email,password_hash,full_name,role) VALUES($1,$2,$3,$4,$5) RETURNING id,email,full_name,role,status`,[s.org_id,email,await bcrypt.hash(temp,12),fullName,role])).rows[0];await audit(s.org_id,null,'scim.user_created','user',user.id,{email});res.status(201).json({schemas:['urn:ietf:params:scim:schemas:core:2.0:User'],id:user.id,userName:user.email,displayName:user.full_name,active:true});}catch(e){res.status(500).json({error:e.message});}});
app.patch('/scim/v2.0/:org/Users/:id',requireDb,async(req,res)=>{try{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});let active=null;for(const op of req.body?.Operations||[]){if(op.path==='active'||op.path==='active '){active=!!op.value;}}if(active===null&&typeof req.body?.active==='boolean')active=req.body.active;const row=(await q(`UPDATE users SET status=CASE WHEN $1::boolean THEN 'active' ELSE 'suspended' END,token_version=CASE WHEN $1::boolean THEN token_version ELSE token_version+1 END WHERE id=$2 AND org_id=$3 RETURNING id,email,full_name,status`,[active!==false,req.params.id,s.org_id])).rows[0];if(!row)return res.status(404).json({error:'User not found'});res.json({id:row.id,userName:row.email,displayName:row.full_name,active:row.status==='active'});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/scim/v2.0/:org/Users/:id',requireDb,async(req,res)=>{try{const s=await scimOrg(req);if(!s||s.slug!==req.params.org)return res.status(401).json({error:'Unauthorized'});const r=await q(`UPDATE users SET status='suspended',token_version=token_version+1 WHERE id=$1 AND org_id=$2 RETURNING id`,[req.params.id,s.org_id]);if(!r.rowCount)return res.status(404).json({error:'User not found'});res.status(204).end();}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/notify/test-email',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const ok=await sendMail(req.body?.to||req.user.email,'DocFlow notification test','Your DocFlow email channel is working.');if(!ok)return res.status(503).json({error:'SMTP is not configured'});await audit(req.user.org_id,req.user.id,'notification.email_test','organization',req.user.org_id,{to:req.body?.to||req.user.email});res.json({ok:true});}catch(e){next(e);}});

function planFromPrice(priceId){
  const map={}; if(process.env.STRIPE_PRICE_STARTER)map[process.env.STRIPE_PRICE_STARTER]='starter'; if(process.env.STRIPE_PRICE_BUSINESS)map[process.env.STRIPE_PRICE_BUSINESS]='business'; if(process.env.STRIPE_PRICE_ENTERPRISE)map[process.env.STRIPE_PRICE_ENTERPRISE]='enterprise'; return map[priceId]||null;
}
async function setOrgPlan(orgId,plan){if(!['trial','starter','business','enterprise'].includes(plan))return;await q('UPDATE organizations SET plan=$1 WHERE id=$2',[plan,orgId]);await audit(orgId,null,'billing.plan_updated','organization',orgId,{plan});}
app.post('/api/billing/stripe/webhook',async(req,res)=>{try{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Stripe webhook not configured');const event=stripe.webhooks.constructEvent(req.rawBody,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);const prior=await q('SELECT id FROM billing_events WHERE provider=$1 AND event_id=$2',['stripe',event.id]);if(prior.rowCount)return res.json({received:true,duplicate:true});const obj=event.data?.object||{};const orgId=obj.metadata?.org_id||obj.subscription_details?.metadata?.org_id||null;await q('INSERT INTO billing_events(provider,event_id,event_type,org_id,payload) VALUES($1,$2,$3,$4,$5)',['stripe',event.id,event.type,orgId,obj]);if(event.type==='checkout.session.completed'&&orgId){await setOrgPlan(orgId,obj.metadata?.plan||process.env.STRIPE_DEFAULT_PLAN||'business');}if(event.type==='customer.subscription.deleted'&&orgId){await setOrgPlan(orgId,'trial');}res.json({received:true});}catch(e){res.status(400).send('Webhook signature verification failed');}});
app.post('/api/billing/create-checkout',requireDb,auth,requireRole('owner'),async(req,res,next)=>{try{if(!stripe)return res.status(503).json({error:'Stripe billing is not configured'});const requestedPlan=['starter','business','enterprise'].includes(req.body?.plan)?req.body.plan:null;const priceByPlan={starter:process.env.STRIPE_PRICE_STARTER,business:process.env.STRIPE_PRICE_BUSINESS,enterprise:process.env.STRIPE_PRICE_ENTERPRISE};const priceId=req.body?.priceId||priceByPlan[requestedPlan]||process.env.STRIPE_DEFAULT_PRICE_ID;if(!priceId)return res.status(400).json({error:'Stripe price ID is not configured'});let customerRow=(await q('SELECT * FROM billing_customers WHERE org_id=$1',[req.user.org_id])).rows[0];let customerId=customerRow?.stripe_customer_id;if(!customerId){const customer=await stripe.customers.create({name:req.user.org_name,email:req.user.email,metadata:{org_id:req.user.org_id}});customerId=customer.id;if(customerRow)await q('UPDATE billing_customers SET stripe_customer_id=$1 WHERE org_id=$2',[customerId,req.user.org_id]);else await q('INSERT INTO billing_customers(org_id,stripe_customer_id,email) VALUES($1,$2,$3)',[req.user.org_id,customerId,req.user.email]);}const session=await stripe.checkout.sessions.create({mode:'subscription',customer:customerId,line_items:[{price:priceId,quantity:1}],success_url:`${process.env.APP_BASE_URL||'http://localhost:3000'}/?billing=success`,cancel_url:`${process.env.APP_BASE_URL||'http://localhost:3000'}/?billing=cancelled`,metadata:{org_id:req.user.org_id,plan:planFromPrice(priceId)||requestedPlan||process.env.STRIPE_DEFAULT_PLAN||'business'}});res.json({url:session.url});}catch(e){next(e);}});
app.post('/api/billing/paystack-initialize',requireDb,auth,requireRole('owner'),async(req,res,next)=>{try{if(!process.env.PAYSTACK_SECRET_KEY)return res.status(503).json({error:'Paystack billing is not configured'});const amount=Number(req.body?.amountKobo);const planCode=req.body?.planCode||process.env.PAYSTACK_PLAN_CODE;const plan=['starter','business','enterprise'].includes(req.body?.plan)?req.body.plan:null;if(!amount&&!planCode)return res.status(400).json({error:'Provide amountKobo or configure PAYSTACK_PLAN_CODE'});const payload={email:req.user.email,amount:amount?String(amount):undefined,plan:planCode||undefined,metadata:{org_id:req.user.org_id,plan:plan||process.env.PAYSTACK_DEFAULT_PLAN||'business'},callback_url:`${process.env.APP_BASE_URL||'http://localhost:3000'}/?billing=paystack`};const r=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'content-type':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok||!body.status)return res.status(400).json({error:body.message||'Paystack initialization failed'});res.json({authorization_url:body.data.authorization_url,reference:body.data.reference});}catch(e){next(e);}});
app.post('/api/billing/paystack/webhook',async(req,res)=>{try{if(!process.env.PAYSTACK_SECRET_KEY)return res.status(503).send('Paystack webhook not configured');const signature=String(req.headers['x-paystack-signature']||'');const expected=crypto.createHmac('sha512',process.env.PAYSTACK_SECRET_KEY).update(req.rawBody||Buffer.from(JSON.stringify(req.body||{}))).digest('hex');const sigBuf=Buffer.from(signature);const expBuf=Buffer.from(expected);if(!signature||sigBuf.length!==expBuf.length||!crypto.timingSafeEqual(sigBuf,expBuf))return res.status(401).send('Invalid signature');const eventId=String(req.body?.data?.reference||req.body?.event||randomToken(12));const prior=await q('SELECT id FROM billing_events WHERE provider=$1 AND event_id=$2',['paystack',eventId]);if(prior.rowCount)return res.json({received:true,duplicate:true});const email=normalizeEmail(req.body?.data?.customer?.email||'');const metaOrgId=String(req.body?.data?.metadata?.org_id||'').trim();let org=null;if(metaOrgId) org=(await q('SELECT id FROM organizations WHERE id=$1',[metaOrgId])).rows[0];if(!org&&email) org=(await q('SELECT o.id FROM organizations o JOIN users u ON u.org_id=o.id WHERE lower(u.email)=lower($1) ORDER BY u.created_at LIMIT 1',[email])).rows[0];await q('INSERT INTO billing_events(provider,event_id,event_type,org_id,payload) VALUES($1,$2,$3,$4,$5)',['paystack',eventId,String(req.body?.event||'unknown'),org?.id||null,req.body||{}]);if(req.body?.event==='charge.success'&&org){await setOrgPlan(org.id,req.body?.data?.metadata?.plan||process.env.PAYSTACK_DEFAULT_PLAN||'business');}res.json({received:true});}catch(e){res.status(400).send('Webhook processing failed');}});
app.get('/api/usage',requireDb,auth,async(req,res,next)=>{try{const u=await usage(req.user.org_id);const org=(await q('SELECT plan FROM organizations WHERE id=$1',[req.user.org_id])).rows[0];res.json({usage:u,plan:org?.plan||'trial',limits:PLAN_LIMITS[org?.plan||'trial']||PLAN_LIMITS.trial});}catch(e){next(e);}});
app.post('/api/documents/:id/reprocess',requireDb,auth,requireRole('member'),async(req,res,next)=>{try{const row=(await q(`SELECT * FROM documents WHERE id=$1 AND org_id=$2`,[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Document not found'});await q(`UPDATE documents SET status='queued',error_message=NULL WHERE id=$1`,[row.id]);await createJob(req.user.org_id,'document.process',{documentId:row.id});await audit(req.user.org_id,req.user.id,'document.reprocess_queued','document',row.id);res.json({ok:true});}catch(e){next(e);}});
app.post('/api/documents/:id/correct',requireDb,auth,requireRole('member'),async(req,res,next)=>{try{const data=jsonSafe(req.body?.extractedData||{});const row=(await q('SELECT * FROM documents WHERE id=$1 AND org_id=$2',[req.params.id,req.user.org_id])).rows[0];if(!row)return res.status(404).json({error:'Document not found'});const version=Number((await q('SELECT COALESCE(MAX(version),0)+1 v FROM document_versions WHERE document_id=$1',[row.id])).rows[0].v);await q(`INSERT INTO document_versions(org_id,document_id,version,changed_by,extracted_data,change_note) VALUES($1,$2,$3,$4,$5,$6)`,[req.user.org_id,row.id,version,req.user.id,data,String(req.body?.note||'Manual correction').slice(0,500)]);await q(`UPDATE documents SET extracted_data=$1,validation_status='valid',validation_errors='[]'::jsonb,status='processed' WHERE id=$2`,[data,row.id]);await audit(req.user.org_id,req.user.id,'document.corrected','document',row.id,{version});res.json({ok:true,version,documentId:row.id});}catch(e){next(e);}});
app.get('/api/documents/:id/versions',requireDb,auth,requireRole('member'),async(req,res,next)=>{try{const rows=await q(`SELECT id,version,changed_by,extracted_data,change_note,created_at FROM document_versions WHERE document_id=$1 AND org_id=$2 ORDER BY version DESC`,[req.params.id,req.user.org_id]);res.json({versions:rows.rows});}catch(e){next(e);}});
app.get('/api/operations',requireDb,auth,requireRole('admin'),async(req,res,next)=>{try{const [jobs,webhooks,runs]=await Promise.all([q(`SELECT status,COUNT(*)::int count FROM job_queue WHERE org_id=$1 GROUP BY status`,[req.user.org_id]),q(`SELECT status,COUNT(*)::int count FROM webhook_deliveries WHERE org_id=$1 GROUP BY status`,[req.user.org_id]),q(`SELECT status,COUNT(*)::int count FROM workflow_runs WHERE org_id=$1 GROUP BY status`,[req.user.org_id])]);res.json({jobs:jobs.rows,webhooks:webhooks.rows,workflowRuns:runs.rows,storageMode,version:VERSION});}catch(e){next(e);}});
app.get('/api/export/documents.json',requireDb,auth,requireRole('admin'),requireScope('exports:read'),async(req,res,next)=>{try{const rows=(await q(`SELECT id,original_name,mime_type,size_bytes,status,document_type,confidence,risk_level,validation_status,validation_errors,extracted_data,created_at,processed_at FROM documents WHERE org_id=$1 ORDER BY created_at DESC`,[req.user.org_id])).rows;res.setHeader('content-type','application/json');res.setHeader('content-disposition','attachment; filename="docflow-export.json"');res.json({exported_at:new Date().toISOString(),organization_id:req.user.org_id,documents:rows});}catch(e){next(e);}});
if(process.env.METRICS_TOKEN){app.get('/metrics',(req,res)=>{if(req.headers.authorization!==`Bearer ${process.env.METRICS_TOKEN}`)return res.status(401).end();res.type('text/plain').send(`# DocFlow metrics\ndocflow_up 1\ndocflow_version{version="${VERSION}"} 1\n`);});}
app.get('/api/config/public',(_req,res)=>res.json({appName:APP_NAME,currency:process.env.CURRENCY||'NGN',trialDays:Number(process.env.TRIAL_DAYS||14),version:VERSION,storage:storageMode,features:{ai:!!process.env.AI_API_KEY,ocr:!!process.env.OCR_API_URL,stripe:!!stripe,paystack:!!process.env.PAYSTACK_SECRET_KEY,smtp:!!process.env.SMTP_HOST,s3:storageMode==='s3',oidc:!!(process.env.OIDC_ISSUER_URL&&process.env.OIDC_CLIENT_ID),scim:!!process.env.SCIM_TOKEN_SECRET},billing:{stripePrices:{starter:process.env.STRIPE_PRICE_STARTER||null,business:process.env.STRIPE_PRICE_BUSINESS||null,enterprise:process.env.STRIPE_PRICE_ENTERPRISE||null},paystackPlanCode:process.env.PAYSTACK_PLAN_CODE||null},limits:PLAN_LIMITS}));

app.use(express.static(path.join(__dirname,'public')));
app.get('/app.css',(_req,res)=>res.sendFile(path.join(__dirname,'app.css')));
app.get('/styles.css',(_req,res)=>res.sendFile(path.join(__dirname,'styles.css')));
app.get('/app.js',(_req,res)=>res.sendFile(path.join(__dirname,'app.js')));
app.get('*',(req,res)=>{if(req.path.startsWith('/api/')||req.path.startsWith('/scim/'))return res.status(404).json({error:'Route not found'});res.sendFile(path.join(__dirname,'index.html'));});
app.use((err,req,res,_next)=>{console.error(`[${req.requestId}]`,err);if(err?.statusCode)return res.status(err.statusCode).json({error:err.message,requestId:req.requestId});if(err instanceof multer.MulterError)return res.status(400).json({error:err.message,requestId:req.requestId});const message=process.env.NODE_ENV==='production'?'Internal server error':err.message;res.status(500).json({error:message,requestId:req.requestId});});

(async()=>{try{await ensureSchema();app.listen(PORT,()=>console.log(`${APP_NAME} ${VERSION} listening on ${PORT}`));}catch(e){console.error(e);process.exit(1);}})();
